
services:
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:postgresql://postgresserver:5432/rekomendasos_db
      DB_USERNAME: postgres
      DB_PASSWORD: Batassuci123#
      REDIS_HOST: redisserver
      REDIS_PORT: 6379
      CLOUDINARY_CLOUD_NAME: dw1lc8ynz
      CLOUDINARY_API_KEY: 543951964988986
      CLOUDINARY_API_SECRET: jl6mqzc8755R2nBAAiEweEqzP94
      JWT_SECRET_KEY: 743777217A25432A462D4A614E635266556A586E3272357538782F413F442847
      JWT_EXPIRATION: 86400000
      JWT_REFRESH_EXPIRATION: 604800000
      MIDTRANS_SERVER_KEY: SB-Mid-server-uqKv7R52RROgL1I0AX_DOcI6
      MIDTRANS_API_URL: https://api.sandbox.midtrans.com/v2/
    depends_on:
      - postgresserver
      - redisserver

  postgresserver:
    container_name: postgresserver
    image: postgres
    environment:
      POSTGRES_PASSWORD: Batassuci123#
      POSTGRES_DB: rekomendasos_db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5

  redisserver:
    container_name: redisserver
    image: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  default:
    driver: bridge
