spring:
  datasource:
#    url: jdbc:postgresql://localhost:5432/java_todo_db?createDatabaseIfNotExist=true
    url: jdbc:postgresql://localhost:5432/rekomendasos_db
    username: postgres
    password: postgres
#    password: Batassuci123#
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
  application:
    name: rekomendasos

application:
  security:
    jwt:
      secret-key: 743777217A25432A462D4A614E635266556A586E3272357538782F413F442847
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
server:
  port: 8088

bezkoder:
  openapi:
    dev-url: http://localhost:8088
    prod-url: https://localhost:8080

logging:
    level:
        org:
        springframework:
            security: DEBUG
            web: DEBUG
            data: DEBUG
            hibernate: DEBUG
            jpa: DEBUG
            sql: DEBUG
            jwt: DEBUG
            bezkoder: DEBUG
cloudinary:
  cloud_name: dw1lc8ynz
  api_key: 543951964988986
  api_secret: jl6mqzc8755R2nBAAiEweEqzP94
