spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
  application:
    name: rekomendasos
  cache:
    type: redis
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}
      expiration: ${JWT_EXPIRATION}
      refresh-token:
        expiration: ${JWT_REFRESH_EXPIRATION}

midtrans:
  server-key: ${MIDTRANS_SERVER_KEY}
  api-url: ${MIDTRANS_API_URL}

server:
  port: 8080

bezkoder:
  openapi:
    dev-url: http://localhost:8088
    prod-url: https://localhost:8080

logging:
  level:
    org:
      springframework:
        security: DEBUG
        web: DEBUG
        data: DEBUG
        hibernate: DEBUG
        jpa: DEBUG
        sql: DEBUG
        jwt: DEBUG
        bezkoder: DEBUG

cloudinary:
  cloud_name: ${CLOUDINARY_CLOUD_NAME}
  api_key: ${CLOUDINARY_API_KEY}
  api_secret: ${CLOUDINARY_API_SECRET}
